name: Mirror to GitLab

on:
  push:
    branches:
      - "**"
    tags:
      - "**"

  workflow_dispatch:

jobs:
  mirror:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Mirror to GitLab
        env:
          GITLAB_TOKEN: ${{ secrets.GITLAB_TOKEN }}
        run: |
          git remote add gitlab "https://oauth2:${GITLAB_TOKEN}@gitlab.com/neikiri/${{ github.event.repository.name }}.git"
          git push --mirror gitlab
